vim.keymap.set("n", "<M-t>", ":ObsidianTemplate _layout_2.md<CR>/o1df<CR>zzcc", {})
vim.keymap.set("n", "<leader>obl", ":ObsidianBacklinks<CR>", {})
vim.keymap.set("n", "<leader>so", ":ObsidianSearch<CR>", {})
vim.keymap.set("v", "<C-t>", ":ObsidianLink<CR>", {})
vim.keymap.set("v", "<C-t><C-n>", ":ObsidianLinkNew<CR>", {})
